services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.multistage
    container_name: tomato-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - food-delivery-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.multistage
    container_name: tomato-admin
    ports:
      - "5174:5174"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - food-delivery-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.multistage
    container_name: tomato-backend
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SALT: ${SALT}
      MONGO_URL: ${MONGO_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    networks:
      - food-delivery-network

  mongodb:
    image: mongo:8
    container_name: tomato-mongodb
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - food-delivery-network

volumes:
  mongodb_data:
  uploads_data:

networks:
  food-delivery-network:
    driver: bridge