#stage 1: Builder
FROM dhi.io/node:24-alpine-dev AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

#stage 2: Running
FROM dhi.io/node:24-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app ./

EXPOSE 4000

CMD ["node", "server.js"]